spring:
  profiles:
    include: oauth

  jpa:
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
        ddl-auto: create
        dialect: org.hibernate.dialect.MySQL57Dialect
        format_sql: true
        use_sql_comments: true # jpql 확인

  h2:
    console:
      enabled: true
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;MODE=MYSQL



logging.level:
  org.hibernate.SQL: debug
  #  org.hibernate.type: trace